package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.CtlOwnerInfo;
import com.fanli.scheduler.entity.CtlOwnerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtlOwnerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int countByExample(CtlOwnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int deleteByExample(CtlOwnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int insert(CtlOwnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int insertSelective(CtlOwnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    List<CtlOwnerInfo> selectByExample(CtlOwnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CtlOwnerInfo record, @Param("example") CtlOwnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    int updateByExample(@Param("record") CtlOwnerInfo record, @Param("example") CtlOwnerInfoExample example);
}