package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.DimTargetHiveDb;
import com.fanli.scheduler.entity.DimTargetHiveDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DimTargetHiveDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int countByExample(DimTargetHiveDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int deleteByExample(DimTargetHiveDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int insert(DimTargetHiveDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int insertSelective(DimTargetHiveDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    List<DimTargetHiveDb> selectByExample(DimTargetHiveDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    DimTargetHiveDb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") DimTargetHiveDb record, @Param("example") DimTargetHiveDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int updateByExample(@Param("record") DimTargetHiveDb record, @Param("example") DimTargetHiveDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int updateByPrimaryKeySelective(DimTargetHiveDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_target_hive_db
     *
     * @mbggenerated Thu Aug 06 13:49:57 CST 2015
     */
    int updateByPrimaryKey(DimTargetHiveDb record);
}