package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlMetaColumn;
import com.fanli.scheduler.entity.EtlMetaColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlMetaColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int countByExample(EtlMetaColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int deleteByExample(EtlMetaColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int insert(EtlMetaColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int insertSelective(EtlMetaColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    List<EtlMetaColumn> selectByExample(EtlMetaColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlMetaColumn record, @Param("example") EtlMetaColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_column
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByExample(@Param("record") EtlMetaColumn record, @Param("example") EtlMetaColumnExample example);
}