package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlMetaHiveTable;
import com.fanli.scheduler.entity.EtlMetaHiveTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlMetaHiveTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int countByExample(EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int deleteByExample(EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int deleteByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int insert(EtlMetaHiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int insertSelective(EtlMetaHiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    List<EtlMetaHiveTable> selectByExampleWithBLOBs(EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    List<EtlMetaHiveTable> selectByExample(EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    EtlMetaHiveTable selectByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlMetaHiveTable record, @Param("example") EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EtlMetaHiveTable record, @Param("example") EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByExample(@Param("record") EtlMetaHiveTable record, @Param("example") EtlMetaHiveTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByPrimaryKeySelective(EtlMetaHiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EtlMetaHiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_hivetable
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    int updateByPrimaryKey(EtlMetaHiveTable record);
}