package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlMetaTableBase;
import com.fanli.scheduler.entity.EtlMetaTableBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlMetaTableBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int countByExample(EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int deleteByExample(EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int deleteByPrimaryKey(Long globalTableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int insert(EtlMetaTableBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int insertSelective(EtlMetaTableBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    List<EtlMetaTableBase> selectByExampleWithBLOBs(EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    List<EtlMetaTableBase> selectByExample(EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    EtlMetaTableBase selectByPrimaryKey(Long globalTableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlMetaTableBase record, @Param("example") EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EtlMetaTableBase record, @Param("example") EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByExample(@Param("record") EtlMetaTableBase record, @Param("example") EtlMetaTableBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByPrimaryKeySelective(EtlMetaTableBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EtlMetaTableBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_table_base
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByPrimaryKey(EtlMetaTableBase record);
}