package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlMonitorDetail;
import com.fanli.scheduler.entity.EtlMonitorDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlMonitorDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int countByExample(EtlMonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int deleteByExample(EtlMonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int insert(EtlMonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int insertSelective(EtlMonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    List<EtlMonitorDetail> selectByExample(EtlMonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    EtlMonitorDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlMonitorDetail record, @Param("example") EtlMonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int updateByExample(@Param("record") EtlMonitorDetail record, @Param("example") EtlMonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int updateByPrimaryKeySelective(EtlMonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor_detail
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    int updateByPrimaryKey(EtlMonitorDetail record);
}