package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlMetaPartition;
import com.fanli.scheduler.entity.EtlMetaPartitionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlMetaPartitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int countByExample(EtlMetaPartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int deleteByExample(EtlMetaPartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int deleteByPrimaryKey(Integer partitionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int insert(EtlMetaPartition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int insertSelective(EtlMetaPartition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    List<EtlMetaPartition> selectByExample(EtlMetaPartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    EtlMetaPartition selectByPrimaryKey(Integer partitionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlMetaPartition record, @Param("example") EtlMetaPartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByExample(@Param("record") EtlMetaPartition record, @Param("example") EtlMetaPartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByPrimaryKeySelective(EtlMetaPartition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_meta_partition
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    int updateByPrimaryKey(EtlMetaPartition record);
}