package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlSourceDim;
import com.fanli.scheduler.entity.EtlSourceDimExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlSourceDimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int countByExample(EtlSourceDimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int deleteByExample(EtlSourceDimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int deleteByPrimaryKey(Integer sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int insert(EtlSourceDim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int insertSelective(EtlSourceDim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    List<EtlSourceDim> selectByExample(EtlSourceDimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    EtlSourceDim selectByPrimaryKey(Integer sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlSourceDim record, @Param("example") EtlSourceDimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int updateByExample(@Param("record") EtlSourceDim record, @Param("example") EtlSourceDimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int updateByPrimaryKeySelective(EtlSourceDim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_source_dim
     *
     * @mbggenerated Tue Aug 11 14:18:13 CST 2015
     */
    int updateByPrimaryKey(EtlSourceDim record);
}