package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.EtlTaskCfg;
import com.fanli.scheduler.entity.EtlTaskCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlTaskCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int countByExample(EtlTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int deleteByExample(EtlTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int insert(EtlTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int insertSelective(EtlTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    List<EtlTaskCfg> selectByExample(EtlTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    EtlTaskCfg selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") EtlTaskCfg record, @Param("example") EtlTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int updateByExample(@Param("record") EtlTaskCfg record, @Param("example") EtlTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int updateByPrimaryKeySelective(EtlTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_task_cfg
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    int updateByPrimaryKey(EtlTaskCfg record);
}