package com.fanli.scheduler.mapping;

import com.fanli.scheduler.entity.MdsItemtable;
import com.fanli.scheduler.entity.MdsItemtableExample;
import com.fanli.scheduler.entity.MdsItemtableWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MdsItemtableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int countByExample(MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int deleteByExample(MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int deleteByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int insert(MdsItemtableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int insertSelective(MdsItemtableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    List<MdsItemtableWithBLOBs> selectByExampleWithBLOBs(MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    List<MdsItemtable> selectByExample(MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    MdsItemtableWithBLOBs selectByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") MdsItemtableWithBLOBs record, @Param("example") MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") MdsItemtableWithBLOBs record, @Param("example") MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByExample(@Param("record") MdsItemtable record, @Param("example") MdsItemtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByPrimaryKeySelective(MdsItemtableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(MdsItemtableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_itemtable
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    int updateByPrimaryKey(MdsItemtable record);
}