package com.fanli.scheduler.entity;

import java.util.Date;

public class CtlOwnerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owner_id
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owner_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.cn_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owner_group
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String ownerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owner_password
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String ownerPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owner_mail_address
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String ownerMailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.owne_mobile
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private String owneMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.is_enable
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.is_interface
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private Boolean isInterface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.ins_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private Date insDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctl_owner_info.upd_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owner_id
     *
     * @return the value of ctl_owner_info.owner_id
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owner_id
     *
     * @param ownerId the value for ctl_owner_info.owner_id
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owner_name
     *
     * @return the value of ctl_owner_info.owner_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owner_name
     *
     * @param ownerName the value for ctl_owner_info.owner_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.cn_name
     *
     * @return the value of ctl_owner_info.cn_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.cn_name
     *
     * @param cnName the value for ctl_owner_info.cn_name
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owner_group
     *
     * @return the value of ctl_owner_info.owner_group
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOwnerGroup() {
        return ownerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owner_group
     *
     * @param ownerGroup the value for ctl_owner_info.owner_group
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwnerGroup(String ownerGroup) {
        this.ownerGroup = ownerGroup == null ? null : ownerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owner_password
     *
     * @return the value of ctl_owner_info.owner_password
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOwnerPassword() {
        return ownerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owner_password
     *
     * @param ownerPassword the value for ctl_owner_info.owner_password
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwnerPassword(String ownerPassword) {
        this.ownerPassword = ownerPassword == null ? null : ownerPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owner_mail_address
     *
     * @return the value of ctl_owner_info.owner_mail_address
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOwnerMailAddress() {
        return ownerMailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owner_mail_address
     *
     * @param ownerMailAddress the value for ctl_owner_info.owner_mail_address
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwnerMailAddress(String ownerMailAddress) {
        this.ownerMailAddress = ownerMailAddress == null ? null : ownerMailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.owne_mobile
     *
     * @return the value of ctl_owner_info.owne_mobile
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOwneMobile() {
        return owneMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.owne_mobile
     *
     * @param owneMobile the value for ctl_owner_info.owne_mobile
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOwneMobile(String owneMobile) {
        this.owneMobile = owneMobile == null ? null : owneMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.is_enable
     *
     * @return the value of ctl_owner_info.is_enable
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.is_enable
     *
     * @param isEnable the value for ctl_owner_info.is_enable
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.is_interface
     *
     * @return the value of ctl_owner_info.is_interface
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Boolean getIsInterface() {
        return isInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.is_interface
     *
     * @param isInterface the value for ctl_owner_info.is_interface
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setIsInterface(Boolean isInterface) {
        this.isInterface = isInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.ins_date
     *
     * @return the value of ctl_owner_info.ins_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.ins_date
     *
     * @param insDate the value for ctl_owner_info.ins_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctl_owner_info.upd_date
     *
     * @return the value of ctl_owner_info.upd_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctl_owner_info.upd_date
     *
     * @param updDate the value for ctl_owner_info.upd_date
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
}