package com.fanli.scheduler.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtlOwnerInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public CtlOwnerInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(Integer value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(Integer value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(Integer value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(Integer value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(Integer value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<Integer> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<Integer> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(Integer value1, Integer value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNull() {
            addCriterion("owner_name is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNotNull() {
            addCriterion("owner_name is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("owner_name =", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotEqualTo(String value) {
            addCriterion("owner_name <>", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThan(String value) {
            addCriterion("owner_name >", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("owner_name >=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThan(String value) {
            addCriterion("owner_name <", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("owner_name <=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLike(String value) {
            addCriterion("owner_name like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotLike(String value) {
            addCriterion("owner_name not like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIn(List<String> values) {
            addCriterion("owner_name in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotIn(List<String> values) {
            addCriterion("owner_name not in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameBetween(String value1, String value2) {
            addCriterion("owner_name between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotBetween(String value1, String value2) {
            addCriterion("owner_name not between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andCnNameIsNull() {
            addCriterion("cn_name is null");
            return (Criteria) this;
        }

        public Criteria andCnNameIsNotNull() {
            addCriterion("cn_name is not null");
            return (Criteria) this;
        }

        public Criteria andCnNameEqualTo(String value) {
            addCriterion("cn_name =", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotEqualTo(String value) {
            addCriterion("cn_name <>", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameGreaterThan(String value) {
            addCriterion("cn_name >", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameGreaterThanOrEqualTo(String value) {
            addCriterion("cn_name >=", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLessThan(String value) {
            addCriterion("cn_name <", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLessThanOrEqualTo(String value) {
            addCriterion("cn_name <=", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLike(String value) {
            addCriterion("cn_name like", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotLike(String value) {
            addCriterion("cn_name not like", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameIn(List<String> values) {
            addCriterion("cn_name in", values, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotIn(List<String> values) {
            addCriterion("cn_name not in", values, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameBetween(String value1, String value2) {
            addCriterion("cn_name between", value1, value2, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotBetween(String value1, String value2) {
            addCriterion("cn_name not between", value1, value2, "cnName");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupIsNull() {
            addCriterion("owner_group is null");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupIsNotNull() {
            addCriterion("owner_group is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupEqualTo(String value) {
            addCriterion("owner_group =", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupNotEqualTo(String value) {
            addCriterion("owner_group <>", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupGreaterThan(String value) {
            addCriterion("owner_group >", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupGreaterThanOrEqualTo(String value) {
            addCriterion("owner_group >=", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupLessThan(String value) {
            addCriterion("owner_group <", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupLessThanOrEqualTo(String value) {
            addCriterion("owner_group <=", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupLike(String value) {
            addCriterion("owner_group like", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupNotLike(String value) {
            addCriterion("owner_group not like", value, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupIn(List<String> values) {
            addCriterion("owner_group in", values, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupNotIn(List<String> values) {
            addCriterion("owner_group not in", values, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupBetween(String value1, String value2) {
            addCriterion("owner_group between", value1, value2, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerGroupNotBetween(String value1, String value2) {
            addCriterion("owner_group not between", value1, value2, "ownerGroup");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordIsNull() {
            addCriterion("owner_password is null");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordIsNotNull() {
            addCriterion("owner_password is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordEqualTo(String value) {
            addCriterion("owner_password =", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordNotEqualTo(String value) {
            addCriterion("owner_password <>", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordGreaterThan(String value) {
            addCriterion("owner_password >", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("owner_password >=", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordLessThan(String value) {
            addCriterion("owner_password <", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordLessThanOrEqualTo(String value) {
            addCriterion("owner_password <=", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordLike(String value) {
            addCriterion("owner_password like", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordNotLike(String value) {
            addCriterion("owner_password not like", value, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordIn(List<String> values) {
            addCriterion("owner_password in", values, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordNotIn(List<String> values) {
            addCriterion("owner_password not in", values, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordBetween(String value1, String value2) {
            addCriterion("owner_password between", value1, value2, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerPasswordNotBetween(String value1, String value2) {
            addCriterion("owner_password not between", value1, value2, "ownerPassword");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressIsNull() {
            addCriterion("owner_mail_address is null");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressIsNotNull() {
            addCriterion("owner_mail_address is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressEqualTo(String value) {
            addCriterion("owner_mail_address =", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressNotEqualTo(String value) {
            addCriterion("owner_mail_address <>", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressGreaterThan(String value) {
            addCriterion("owner_mail_address >", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("owner_mail_address >=", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressLessThan(String value) {
            addCriterion("owner_mail_address <", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressLessThanOrEqualTo(String value) {
            addCriterion("owner_mail_address <=", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressLike(String value) {
            addCriterion("owner_mail_address like", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressNotLike(String value) {
            addCriterion("owner_mail_address not like", value, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressIn(List<String> values) {
            addCriterion("owner_mail_address in", values, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressNotIn(List<String> values) {
            addCriterion("owner_mail_address not in", values, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressBetween(String value1, String value2) {
            addCriterion("owner_mail_address between", value1, value2, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwnerMailAddressNotBetween(String value1, String value2) {
            addCriterion("owner_mail_address not between", value1, value2, "ownerMailAddress");
            return (Criteria) this;
        }

        public Criteria andOwneMobileIsNull() {
            addCriterion("owne_mobile is null");
            return (Criteria) this;
        }

        public Criteria andOwneMobileIsNotNull() {
            addCriterion("owne_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andOwneMobileEqualTo(String value) {
            addCriterion("owne_mobile =", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileNotEqualTo(String value) {
            addCriterion("owne_mobile <>", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileGreaterThan(String value) {
            addCriterion("owne_mobile >", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileGreaterThanOrEqualTo(String value) {
            addCriterion("owne_mobile >=", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileLessThan(String value) {
            addCriterion("owne_mobile <", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileLessThanOrEqualTo(String value) {
            addCriterion("owne_mobile <=", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileLike(String value) {
            addCriterion("owne_mobile like", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileNotLike(String value) {
            addCriterion("owne_mobile not like", value, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileIn(List<String> values) {
            addCriterion("owne_mobile in", values, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileNotIn(List<String> values) {
            addCriterion("owne_mobile not in", values, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileBetween(String value1, String value2) {
            addCriterion("owne_mobile between", value1, value2, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andOwneMobileNotBetween(String value1, String value2) {
            addCriterion("owne_mobile not between", value1, value2, "owneMobile");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("is_enable is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("is_enable is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(Boolean value) {
            addCriterion("is_enable =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(Boolean value) {
            addCriterion("is_enable <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(Boolean value) {
            addCriterion("is_enable >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_enable >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(Boolean value) {
            addCriterion("is_enable <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("is_enable <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<Boolean> values) {
            addCriterion("is_enable in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<Boolean> values) {
            addCriterion("is_enable not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enable between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enable not between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceIsNull() {
            addCriterion("is_interface is null");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceIsNotNull() {
            addCriterion("is_interface is not null");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceEqualTo(Boolean value) {
            addCriterion("is_interface =", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceNotEqualTo(Boolean value) {
            addCriterion("is_interface <>", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceGreaterThan(Boolean value) {
            addCriterion("is_interface >", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_interface >=", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceLessThan(Boolean value) {
            addCriterion("is_interface <", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceLessThanOrEqualTo(Boolean value) {
            addCriterion("is_interface <=", value, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceIn(List<Boolean> values) {
            addCriterion("is_interface in", values, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceNotIn(List<Boolean> values) {
            addCriterion("is_interface not in", values, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceBetween(Boolean value1, Boolean value2) {
            addCriterion("is_interface between", value1, value2, "isInterface");
            return (Criteria) this;
        }

        public Criteria andIsInterfaceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_interface not between", value1, value2, "isInterface");
            return (Criteria) this;
        }

        public Criteria andInsDateIsNull() {
            addCriterion("ins_date is null");
            return (Criteria) this;
        }

        public Criteria andInsDateIsNotNull() {
            addCriterion("ins_date is not null");
            return (Criteria) this;
        }

        public Criteria andInsDateEqualTo(Date value) {
            addCriterion("ins_date =", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotEqualTo(Date value) {
            addCriterion("ins_date <>", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateGreaterThan(Date value) {
            addCriterion("ins_date >", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ins_date >=", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateLessThan(Date value) {
            addCriterion("ins_date <", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateLessThanOrEqualTo(Date value) {
            addCriterion("ins_date <=", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateIn(List<Date> values) {
            addCriterion("ins_date in", values, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotIn(List<Date> values) {
            addCriterion("ins_date not in", values, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateBetween(Date value1, Date value2) {
            addCriterion("ins_date between", value1, value2, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotBetween(Date value1, Date value2) {
            addCriterion("ins_date not between", value1, value2, "insDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNull() {
            addCriterion("upd_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNotNull() {
            addCriterion("upd_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDateEqualTo(Date value) {
            addCriterion("upd_date =", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotEqualTo(Date value) {
            addCriterion("upd_date <>", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThan(Date value) {
            addCriterion("upd_date >", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_date >=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThan(Date value) {
            addCriterion("upd_date <", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("upd_date <=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateIn(List<Date> values) {
            addCriterion("upd_date in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotIn(List<Date> values) {
            addCriterion("upd_date not in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateBetween(Date value1, Date value2) {
            addCriterion("upd_date between", value1, value2, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("upd_date not between", value1, value2, "updDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctl_owner_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:44:52 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctl_owner_info
     *
     * @mbggenerated Thu Nov 26 10:44:52 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}