package com.fanli.scheduler.entity;

import java.util.Date;

public class DimDateDeveloper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.id
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.ch_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private String chName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.domain_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.imo
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private String imo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.phone
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_data_developer.updateTime
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.id
     *
     * @return the value of dim_data_developer.id
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.id
     *
     * @param id the value for dim_data_developer.id
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.ch_name
     *
     * @return the value of dim_data_developer.ch_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public String getChName() {
        return chName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.ch_name
     *
     * @param chName the value for dim_data_developer.ch_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setChName(String chName) {
        this.chName = chName == null ? null : chName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.domain_name
     *
     * @return the value of dim_data_developer.domain_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.domain_name
     *
     * @param domainName the value for dim_data_developer.domain_name
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.imo
     *
     * @return the value of dim_data_developer.imo
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public String getImo() {
        return imo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.imo
     *
     * @param imo the value for dim_data_developer.imo
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setImo(String imo) {
        this.imo = imo == null ? null : imo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.phone
     *
     * @return the value of dim_data_developer.phone
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.phone
     *
     * @param phone the value for dim_data_developer.phone
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_data_developer.updateTime
     *
     * @return the value of dim_data_developer.updateTime
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_data_developer.updateTime
     *
     * @param updatetime the value for dim_data_developer.updateTime
     *
     * @mbggenerated Mon Aug 10 17:49:40 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}