package com.fanli.scheduler.entity;

import java.util.Date;

public class EtlLoadCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.task_id
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.parameter_map
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private String parameterMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.type
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.is_valid
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.create_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_load_cfg.update_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.task_id
     *
     * @return the value of etl_load_cfg.task_id
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.task_id
     *
     * @param taskId the value for etl_load_cfg.task_id
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.parameter_map
     *
     * @return the value of etl_load_cfg.parameter_map
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public String getParameterMap() {
        return parameterMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.parameter_map
     *
     * @param parameterMap the value for etl_load_cfg.parameter_map
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setParameterMap(String parameterMap) {
        this.parameterMap = parameterMap == null ? null : parameterMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.type
     *
     * @return the value of etl_load_cfg.type
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.type
     *
     * @param type the value for etl_load_cfg.type
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.is_valid
     *
     * @return the value of etl_load_cfg.is_valid
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.is_valid
     *
     * @param isValid the value for etl_load_cfg.is_valid
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.create_time
     *
     * @return the value of etl_load_cfg.create_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.create_time
     *
     * @param createTime the value for etl_load_cfg.create_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_load_cfg.update_time
     *
     * @return the value of etl_load_cfg.update_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_load_cfg.update_time
     *
     * @param updateTime the value for etl_load_cfg.update_time
     *
     * @mbggenerated Wed Aug 12 09:21:39 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}