package com.fanli.scheduler.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EtlMonitorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public EtlMonitorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(Long value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(Long value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(Long value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(Long value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<Long> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<Long> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(Long value1, Long value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNull() {
            addCriterion("owner_name is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNotNull() {
            addCriterion("owner_name is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("owner_name =", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotEqualTo(String value) {
            addCriterion("owner_name <>", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThan(String value) {
            addCriterion("owner_name >", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("owner_name >=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThan(String value) {
            addCriterion("owner_name <", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("owner_name <=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLike(String value) {
            addCriterion("owner_name like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotLike(String value) {
            addCriterion("owner_name not like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIn(List<String> values) {
            addCriterion("owner_name in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotIn(List<String> values) {
            addCriterion("owner_name not in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameBetween(String value1, String value2) {
            addCriterion("owner_name between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotBetween(String value1, String value2) {
            addCriterion("owner_name not between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMailToIsNull() {
            addCriterion("mail_to is null");
            return (Criteria) this;
        }

        public Criteria andMailToIsNotNull() {
            addCriterion("mail_to is not null");
            return (Criteria) this;
        }

        public Criteria andMailToEqualTo(String value) {
            addCriterion("mail_to =", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToNotEqualTo(String value) {
            addCriterion("mail_to <>", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToGreaterThan(String value) {
            addCriterion("mail_to >", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToGreaterThanOrEqualTo(String value) {
            addCriterion("mail_to >=", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToLessThan(String value) {
            addCriterion("mail_to <", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToLessThanOrEqualTo(String value) {
            addCriterion("mail_to <=", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToLike(String value) {
            addCriterion("mail_to like", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToNotLike(String value) {
            addCriterion("mail_to not like", value, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToIn(List<String> values) {
            addCriterion("mail_to in", values, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToNotIn(List<String> values) {
            addCriterion("mail_to not in", values, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToBetween(String value1, String value2) {
            addCriterion("mail_to between", value1, value2, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailToNotBetween(String value1, String value2) {
            addCriterion("mail_to not between", value1, value2, "mailTo");
            return (Criteria) this;
        }

        public Criteria andMailCcIsNull() {
            addCriterion("mail_cc is null");
            return (Criteria) this;
        }

        public Criteria andMailCcIsNotNull() {
            addCriterion("mail_cc is not null");
            return (Criteria) this;
        }

        public Criteria andMailCcEqualTo(String value) {
            addCriterion("mail_cc =", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcNotEqualTo(String value) {
            addCriterion("mail_cc <>", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcGreaterThan(String value) {
            addCriterion("mail_cc >", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcGreaterThanOrEqualTo(String value) {
            addCriterion("mail_cc >=", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcLessThan(String value) {
            addCriterion("mail_cc <", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcLessThanOrEqualTo(String value) {
            addCriterion("mail_cc <=", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcLike(String value) {
            addCriterion("mail_cc like", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcNotLike(String value) {
            addCriterion("mail_cc not like", value, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcIn(List<String> values) {
            addCriterion("mail_cc in", values, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcNotIn(List<String> values) {
            addCriterion("mail_cc not in", values, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcBetween(String value1, String value2) {
            addCriterion("mail_cc between", value1, value2, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailCcNotBetween(String value1, String value2) {
            addCriterion("mail_cc not between", value1, value2, "mailCc");
            return (Criteria) this;
        }

        public Criteria andMailBccIsNull() {
            addCriterion("mail_bcc is null");
            return (Criteria) this;
        }

        public Criteria andMailBccIsNotNull() {
            addCriterion("mail_bcc is not null");
            return (Criteria) this;
        }

        public Criteria andMailBccEqualTo(String value) {
            addCriterion("mail_bcc =", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccNotEqualTo(String value) {
            addCriterion("mail_bcc <>", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccGreaterThan(String value) {
            addCriterion("mail_bcc >", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccGreaterThanOrEqualTo(String value) {
            addCriterion("mail_bcc >=", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccLessThan(String value) {
            addCriterion("mail_bcc <", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccLessThanOrEqualTo(String value) {
            addCriterion("mail_bcc <=", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccLike(String value) {
            addCriterion("mail_bcc like", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccNotLike(String value) {
            addCriterion("mail_bcc not like", value, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccIn(List<String> values) {
            addCriterion("mail_bcc in", values, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccNotIn(List<String> values) {
            addCriterion("mail_bcc not in", values, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccBetween(String value1, String value2) {
            addCriterion("mail_bcc between", value1, value2, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailBccNotBetween(String value1, String value2) {
            addCriterion("mail_bcc not between", value1, value2, "mailBcc");
            return (Criteria) this;
        }

        public Criteria andMailSubjectIsNull() {
            addCriterion("mail_subject is null");
            return (Criteria) this;
        }

        public Criteria andMailSubjectIsNotNull() {
            addCriterion("mail_subject is not null");
            return (Criteria) this;
        }

        public Criteria andMailSubjectEqualTo(String value) {
            addCriterion("mail_subject =", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectNotEqualTo(String value) {
            addCriterion("mail_subject <>", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectGreaterThan(String value) {
            addCriterion("mail_subject >", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("mail_subject >=", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectLessThan(String value) {
            addCriterion("mail_subject <", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectLessThanOrEqualTo(String value) {
            addCriterion("mail_subject <=", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectLike(String value) {
            addCriterion("mail_subject like", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectNotLike(String value) {
            addCriterion("mail_subject not like", value, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectIn(List<String> values) {
            addCriterion("mail_subject in", values, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectNotIn(List<String> values) {
            addCriterion("mail_subject not in", values, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectBetween(String value1, String value2) {
            addCriterion("mail_subject between", value1, value2, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailSubjectNotBetween(String value1, String value2) {
            addCriterion("mail_subject not between", value1, value2, "mailSubject");
            return (Criteria) this;
        }

        public Criteria andMailMessageIsNull() {
            addCriterion("mail_message is null");
            return (Criteria) this;
        }

        public Criteria andMailMessageIsNotNull() {
            addCriterion("mail_message is not null");
            return (Criteria) this;
        }

        public Criteria andMailMessageEqualTo(String value) {
            addCriterion("mail_message =", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageNotEqualTo(String value) {
            addCriterion("mail_message <>", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageGreaterThan(String value) {
            addCriterion("mail_message >", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageGreaterThanOrEqualTo(String value) {
            addCriterion("mail_message >=", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageLessThan(String value) {
            addCriterion("mail_message <", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageLessThanOrEqualTo(String value) {
            addCriterion("mail_message <=", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageLike(String value) {
            addCriterion("mail_message like", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageNotLike(String value) {
            addCriterion("mail_message not like", value, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageIn(List<String> values) {
            addCriterion("mail_message in", values, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageNotIn(List<String> values) {
            addCriterion("mail_message not in", values, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageBetween(String value1, String value2) {
            addCriterion("mail_message between", value1, value2, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andMailMessageNotBetween(String value1, String value2) {
            addCriterion("mail_message not between", value1, value2, "mailMessage");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andLastLogIsNull() {
            addCriterion("last_log is null");
            return (Criteria) this;
        }

        public Criteria andLastLogIsNotNull() {
            addCriterion("last_log is not null");
            return (Criteria) this;
        }

        public Criteria andLastLogEqualTo(String value) {
            addCriterion("last_log =", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogNotEqualTo(String value) {
            addCriterion("last_log <>", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogGreaterThan(String value) {
            addCriterion("last_log >", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogGreaterThanOrEqualTo(String value) {
            addCriterion("last_log >=", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogLessThan(String value) {
            addCriterion("last_log <", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogLessThanOrEqualTo(String value) {
            addCriterion("last_log <=", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogLike(String value) {
            addCriterion("last_log like", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogNotLike(String value) {
            addCriterion("last_log not like", value, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogIn(List<String> values) {
            addCriterion("last_log in", values, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogNotIn(List<String> values) {
            addCriterion("last_log not in", values, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogBetween(String value1, String value2) {
            addCriterion("last_log between", value1, value2, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastLogNotBetween(String value1, String value2) {
            addCriterion("last_log not between", value1, value2, "lastLog");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeIsNull() {
            addCriterion("last_start_time is null");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeIsNotNull() {
            addCriterion("last_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeEqualTo(Date value) {
            addCriterion("last_start_time =", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeNotEqualTo(Date value) {
            addCriterion("last_start_time <>", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeGreaterThan(Date value) {
            addCriterion("last_start_time >", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_start_time >=", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeLessThan(Date value) {
            addCriterion("last_start_time <", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_start_time <=", value, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeIn(List<Date> values) {
            addCriterion("last_start_time in", values, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeNotIn(List<Date> values) {
            addCriterion("last_start_time not in", values, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeBetween(Date value1, Date value2) {
            addCriterion("last_start_time between", value1, value2, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_start_time not between", value1, value2, "lastStartTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeIsNull() {
            addCriterion("last_end_time is null");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeIsNotNull() {
            addCriterion("last_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeEqualTo(Date value) {
            addCriterion("last_end_time =", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeNotEqualTo(Date value) {
            addCriterion("last_end_time <>", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeGreaterThan(Date value) {
            addCriterion("last_end_time >", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_end_time >=", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeLessThan(Date value) {
            addCriterion("last_end_time <", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_end_time <=", value, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeIn(List<Date> values) {
            addCriterion("last_end_time in", values, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeNotIn(List<Date> values) {
            addCriterion("last_end_time not in", values, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeBetween(Date value1, Date value2) {
            addCriterion("last_end_time between", value1, value2, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andLastEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_end_time not between", value1, value2, "lastEndTime");
            return (Criteria) this;
        }

        public Criteria andInsDateIsNull() {
            addCriterion("ins_date is null");
            return (Criteria) this;
        }

        public Criteria andInsDateIsNotNull() {
            addCriterion("ins_date is not null");
            return (Criteria) this;
        }

        public Criteria andInsDateEqualTo(Date value) {
            addCriterion("ins_date =", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotEqualTo(Date value) {
            addCriterion("ins_date <>", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateGreaterThan(Date value) {
            addCriterion("ins_date >", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ins_date >=", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateLessThan(Date value) {
            addCriterion("ins_date <", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateLessThanOrEqualTo(Date value) {
            addCriterion("ins_date <=", value, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateIn(List<Date> values) {
            addCriterion("ins_date in", values, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotIn(List<Date> values) {
            addCriterion("ins_date not in", values, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateBetween(Date value1, Date value2) {
            addCriterion("ins_date between", value1, value2, "insDate");
            return (Criteria) this;
        }

        public Criteria andInsDateNotBetween(Date value1, Date value2) {
            addCriterion("ins_date not between", value1, value2, "insDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNull() {
            addCriterion("upd_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNotNull() {
            addCriterion("upd_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDateEqualTo(Date value) {
            addCriterion("upd_date =", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotEqualTo(Date value) {
            addCriterion("upd_date <>", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThan(Date value) {
            addCriterion("upd_date >", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_date >=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThan(Date value) {
            addCriterion("upd_date <", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("upd_date <=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateIn(List<Date> values) {
            addCriterion("upd_date in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotIn(List<Date> values) {
            addCriterion("upd_date not in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateBetween(Date value1, Date value2) {
            addCriterion("upd_date between", value1, value2, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("upd_date not between", value1, value2, "updDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_etl_monitor
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 27 17:15:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_etl_monitor
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}