package com.fanli.scheduler.entity;

import java.util.Date;

public class EtlMonitorDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.monitor_id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private Long monitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.title
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.datasource
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private String datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.db
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private String db;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.excute_sql
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private String excuteSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.contrast
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private String contrast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.ins_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private Date insDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_etl_monitor_detail.upd_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.id
     *
     * @return the value of t_etl_monitor_detail.id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.id
     *
     * @param id the value for t_etl_monitor_detail.id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.monitor_id
     *
     * @return the value of t_etl_monitor_detail.monitor_id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Long getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.monitor_id
     *
     * @param monitorId the value for t_etl_monitor_detail.monitor_id
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setMonitorId(Long monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.title
     *
     * @return the value of t_etl_monitor_detail.title
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.title
     *
     * @param title the value for t_etl_monitor_detail.title
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.datasource
     *
     * @return the value of t_etl_monitor_detail.datasource
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.datasource
     *
     * @param datasource the value for t_etl_monitor_detail.datasource
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.db
     *
     * @return the value of t_etl_monitor_detail.db
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getDb() {
        return db;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.db
     *
     * @param db the value for t_etl_monitor_detail.db
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setDb(String db) {
        this.db = db == null ? null : db.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.excute_sql
     *
     * @return the value of t_etl_monitor_detail.excute_sql
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getExcuteSql() {
        return excuteSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.excute_sql
     *
     * @param excuteSql the value for t_etl_monitor_detail.excute_sql
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setExcuteSql(String excuteSql) {
        this.excuteSql = excuteSql == null ? null : excuteSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.contrast
     *
     * @return the value of t_etl_monitor_detail.contrast
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public String getContrast() {
        return contrast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.contrast
     *
     * @param contrast the value for t_etl_monitor_detail.contrast
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setContrast(String contrast) {
        this.contrast = contrast == null ? null : contrast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.ins_date
     *
     * @return the value of t_etl_monitor_detail.ins_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.ins_date
     *
     * @param insDate the value for t_etl_monitor_detail.ins_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_etl_monitor_detail.upd_date
     *
     * @return the value of t_etl_monitor_detail.upd_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_etl_monitor_detail.upd_date
     *
     * @param updDate the value for t_etl_monitor_detail.upd_date
     *
     * @mbggenerated Fri Nov 27 17:15:13 CST 2015
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
}