package com.fanli.scheduler.entity;

import java.util.Date;

public class EtlMetaTableBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.job_id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.table_name
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.db
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String db;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.storage_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String storageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.developer
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String developer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.owner
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.task_status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Integer taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.refresh_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String refreshType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.refresh_offset
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String refreshOffset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.refresh_cycle
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String refreshCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.is_partition_table
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Byte isPartitionTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.data_last_refresh_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Date dataLastRefreshTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.table_access_code
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Integer tableAccessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.add_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.update_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_table_base.table_comment
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    private String tableComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.id
     *
     * @return the value of etl_meta_table_base.id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.id
     *
     * @param id the value for etl_meta_table_base.id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.job_id
     *
     * @return the value of etl_meta_table_base.job_id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.job_id
     *
     * @param jobId the value for etl_meta_table_base.job_id
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.table_name
     *
     * @return the value of etl_meta_table_base.table_name
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.table_name
     *
     * @param tableName the value for etl_meta_table_base.table_name
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.db
     *
     * @return the value of etl_meta_table_base.db
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getDb() {
        return db;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.db
     *
     * @param db the value for etl_meta_table_base.db
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setDb(String db) {
        this.db = db == null ? null : db.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.storage_type
     *
     * @return the value of etl_meta_table_base.storage_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.storage_type
     *
     * @param storageType the value for etl_meta_table_base.storage_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType == null ? null : storageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.developer
     *
     * @return the value of etl_meta_table_base.developer
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.developer
     *
     * @param developer the value for etl_meta_table_base.developer
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setDeveloper(String developer) {
        this.developer = developer == null ? null : developer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.owner
     *
     * @return the value of etl_meta_table_base.owner
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.owner
     *
     * @param owner the value for etl_meta_table_base.owner
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.task_status
     *
     * @return the value of etl_meta_table_base.task_status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.task_status
     *
     * @param taskStatus the value for etl_meta_table_base.task_status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.refresh_type
     *
     * @return the value of etl_meta_table_base.refresh_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getRefreshType() {
        return refreshType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.refresh_type
     *
     * @param refreshType the value for etl_meta_table_base.refresh_type
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setRefreshType(String refreshType) {
        this.refreshType = refreshType == null ? null : refreshType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.refresh_offset
     *
     * @return the value of etl_meta_table_base.refresh_offset
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getRefreshOffset() {
        return refreshOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.refresh_offset
     *
     * @param refreshOffset the value for etl_meta_table_base.refresh_offset
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setRefreshOffset(String refreshOffset) {
        this.refreshOffset = refreshOffset == null ? null : refreshOffset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.refresh_cycle
     *
     * @return the value of etl_meta_table_base.refresh_cycle
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getRefreshCycle() {
        return refreshCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.refresh_cycle
     *
     * @param refreshCycle the value for etl_meta_table_base.refresh_cycle
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setRefreshCycle(String refreshCycle) {
        this.refreshCycle = refreshCycle == null ? null : refreshCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.status
     *
     * @return the value of etl_meta_table_base.status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.status
     *
     * @param status the value for etl_meta_table_base.status
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.is_partition_table
     *
     * @return the value of etl_meta_table_base.is_partition_table
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Byte getIsPartitionTable() {
        return isPartitionTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.is_partition_table
     *
     * @param isPartitionTable the value for etl_meta_table_base.is_partition_table
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setIsPartitionTable(Byte isPartitionTable) {
        this.isPartitionTable = isPartitionTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.data_last_refresh_time
     *
     * @return the value of etl_meta_table_base.data_last_refresh_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Date getDataLastRefreshTime() {
        return dataLastRefreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.data_last_refresh_time
     *
     * @param dataLastRefreshTime the value for etl_meta_table_base.data_last_refresh_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setDataLastRefreshTime(Date dataLastRefreshTime) {
        this.dataLastRefreshTime = dataLastRefreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.table_access_code
     *
     * @return the value of etl_meta_table_base.table_access_code
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Integer getTableAccessCode() {
        return tableAccessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.table_access_code
     *
     * @param tableAccessCode the value for etl_meta_table_base.table_access_code
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setTableAccessCode(Integer tableAccessCode) {
        this.tableAccessCode = tableAccessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.add_time
     *
     * @return the value of etl_meta_table_base.add_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.add_time
     *
     * @param addTime the value for etl_meta_table_base.add_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.update_time
     *
     * @return the value of etl_meta_table_base.update_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.update_time
     *
     * @param updateTime the value for etl_meta_table_base.update_time
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_table_base.table_comment
     *
     * @return the value of etl_meta_table_base.table_comment
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public String getTableComment() {
        return tableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_table_base.table_comment
     *
     * @param tableComment the value for etl_meta_table_base.table_comment
     *
     * @mbggenerated Wed Sep 30 14:50:33 CST 2015
     */
    public void setTableComment(String tableComment) {
        this.tableComment = tableComment == null ? null : tableComment.trim();
    }
}