package com.fanli.scheduler.entity;

public class EtlMetaPartition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_partition.partition_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Integer partitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_partition.partition_name
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String partitionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_partition.partition_create_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String partitionCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_partition.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Integer tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_partition.add_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_partition.partition_id
     *
     * @return the value of etl_meta_partition.partition_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Integer getPartitionId() {
        return partitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_partition.partition_id
     *
     * @param partitionId the value for etl_meta_partition.partition_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setPartitionId(Integer partitionId) {
        this.partitionId = partitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_partition.partition_name
     *
     * @return the value of etl_meta_partition.partition_name
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getPartitionName() {
        return partitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_partition.partition_name
     *
     * @param partitionName the value for etl_meta_partition.partition_name
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setPartitionName(String partitionName) {
        this.partitionName = partitionName == null ? null : partitionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_partition.partition_create_time
     *
     * @return the value of etl_meta_partition.partition_create_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getPartitionCreateTime() {
        return partitionCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_partition.partition_create_time
     *
     * @param partitionCreateTime the value for etl_meta_partition.partition_create_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setPartitionCreateTime(String partitionCreateTime) {
        this.partitionCreateTime = partitionCreateTime == null ? null : partitionCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_partition.table_id
     *
     * @return the value of etl_meta_partition.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_partition.table_id
     *
     * @param tableId the value for etl_meta_partition.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_partition.add_time
     *
     * @return the value of etl_meta_partition.add_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_partition.add_time
     *
     * @param addTime the value for etl_meta_partition.add_time
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }
}