package com.fanli.scheduler.entity;

public class EtlMetaHiveTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Long globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Integer tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.hive_db
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String hiveDb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.input_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String inputFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.output_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String outputFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.hdfs_location
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String hdfsLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.table_type
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String tableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.field_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String fieldTerminated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.line_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String lineTerminated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.store_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String storeFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_hivetable.ddl_with_change
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private String ddlWithChange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.global_id
     *
     * @return the value of etl_meta_hivetable.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Long getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.global_id
     *
     * @param globalId the value for etl_meta_hivetable.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.table_id
     *
     * @return the value of etl_meta_hivetable.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.table_id
     *
     * @param tableId the value for etl_meta_hivetable.table_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.hive_db
     *
     * @return the value of etl_meta_hivetable.hive_db
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getHiveDb() {
        return hiveDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.hive_db
     *
     * @param hiveDb the value for etl_meta_hivetable.hive_db
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setHiveDb(String hiveDb) {
        this.hiveDb = hiveDb == null ? null : hiveDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.input_format
     *
     * @return the value of etl_meta_hivetable.input_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getInputFormat() {
        return inputFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.input_format
     *
     * @param inputFormat the value for etl_meta_hivetable.input_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setInputFormat(String inputFormat) {
        this.inputFormat = inputFormat == null ? null : inputFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.output_format
     *
     * @return the value of etl_meta_hivetable.output_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.output_format
     *
     * @param outputFormat the value for etl_meta_hivetable.output_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setOutputFormat(String outputFormat) {
        this.outputFormat = outputFormat == null ? null : outputFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.hdfs_location
     *
     * @return the value of etl_meta_hivetable.hdfs_location
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getHdfsLocation() {
        return hdfsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.hdfs_location
     *
     * @param hdfsLocation the value for etl_meta_hivetable.hdfs_location
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setHdfsLocation(String hdfsLocation) {
        this.hdfsLocation = hdfsLocation == null ? null : hdfsLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.table_type
     *
     * @return the value of etl_meta_hivetable.table_type
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.table_type
     *
     * @param tableType the value for etl_meta_hivetable.table_type
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setTableType(String tableType) {
        this.tableType = tableType == null ? null : tableType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.field_terminated
     *
     * @return the value of etl_meta_hivetable.field_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getFieldTerminated() {
        return fieldTerminated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.field_terminated
     *
     * @param fieldTerminated the value for etl_meta_hivetable.field_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setFieldTerminated(String fieldTerminated) {
        this.fieldTerminated = fieldTerminated == null ? null : fieldTerminated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.line_terminated
     *
     * @return the value of etl_meta_hivetable.line_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getLineTerminated() {
        return lineTerminated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.line_terminated
     *
     * @param lineTerminated the value for etl_meta_hivetable.line_terminated
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setLineTerminated(String lineTerminated) {
        this.lineTerminated = lineTerminated == null ? null : lineTerminated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.store_format
     *
     * @return the value of etl_meta_hivetable.store_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getStoreFormat() {
        return storeFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.store_format
     *
     * @param storeFormat the value for etl_meta_hivetable.store_format
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setStoreFormat(String storeFormat) {
        this.storeFormat = storeFormat == null ? null : storeFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_hivetable.ddl_with_change
     *
     * @return the value of etl_meta_hivetable.ddl_with_change
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public String getDdlWithChange() {
        return ddlWithChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_hivetable.ddl_with_change
     *
     * @param ddlWithChange the value for etl_meta_hivetable.ddl_with_change
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setDdlWithChange(String ddlWithChange) {
        this.ddlWithChange = ddlWithChange == null ? null : ddlWithChange.trim();
    }
}