package com.fanli.scheduler.entity;

public class EtlMetaColumnKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_column.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Long globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_meta_column.column_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    private Integer columnId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_column.global_id
     *
     * @return the value of etl_meta_column.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Long getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_column.global_id
     *
     * @param globalId the value for etl_meta_column.global_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_meta_column.column_id
     *
     * @return the value of etl_meta_column.column_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_meta_column.column_id
     *
     * @param columnId the value for etl_meta_column.column_id
     *
     * @mbggenerated Fri Oct 09 11:14:50 CST 2015
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }
}