package com.fanli.scheduler.entity;

import java.util.Date;

public class EtlSystemFeedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.id
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.comment
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.title
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.user
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.add_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_system_feedback.update_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.id
     *
     * @return the value of etl_system_feedback.id
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.id
     *
     * @param id the value for etl_system_feedback.id
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.comment
     *
     * @return the value of etl_system_feedback.comment
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.comment
     *
     * @param comment the value for etl_system_feedback.comment
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.title
     *
     * @return the value of etl_system_feedback.title
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.title
     *
     * @param title the value for etl_system_feedback.title
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.user
     *
     * @return the value of etl_system_feedback.user
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.user
     *
     * @param user the value for etl_system_feedback.user
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.add_time
     *
     * @return the value of etl_system_feedback.add_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.add_time
     *
     * @param addTime the value for etl_system_feedback.add_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_system_feedback.update_time
     *
     * @return the value of etl_system_feedback.update_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_system_feedback.update_time
     *
     * @param updateTime the value for etl_system_feedback.update_time
     *
     * @mbggenerated Fri Oct 09 23:22:08 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}