package com.fanli.scheduler.entity;

import java.util.Date;

public class EtlTaskCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.task_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.task_group_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer taskGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.task_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.table_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.resource
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.command
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String command;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.cycle
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.priority
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.if_recall
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer ifRecall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.if_wait
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer ifWait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.if_pre
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer ifPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.if_enable
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer ifEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.freq
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String freq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.owner
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.wait_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String waitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.recall_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String recallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.success_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String successCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.timeout
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.recall_interval
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer recallInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.log_file
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String logFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.add_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.add_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.update_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.update_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.type
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.offset
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private String offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.recall_limit
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer recallLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etl_task_cfg.concurrency
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    private Integer concurrency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.task_id
     *
     * @return the value of etl_task_cfg.task_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.task_id
     *
     * @param taskId the value for etl_task_cfg.task_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.task_group_id
     *
     * @return the value of etl_task_cfg.task_group_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getTaskGroupId() {
        return taskGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.task_group_id
     *
     * @param taskGroupId the value for etl_task_cfg.task_group_id
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setTaskGroupId(Integer taskGroupId) {
        this.taskGroupId = taskGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.task_name
     *
     * @return the value of etl_task_cfg.task_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.task_name
     *
     * @param taskName the value for etl_task_cfg.task_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.table_name
     *
     * @return the value of etl_task_cfg.table_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.table_name
     *
     * @param tableName the value for etl_task_cfg.table_name
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.resource
     *
     * @return the value of etl_task_cfg.resource
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.resource
     *
     * @param resource the value for etl_task_cfg.resource
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.command
     *
     * @return the value of etl_task_cfg.command
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.command
     *
     * @param command the value for etl_task_cfg.command
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.cycle
     *
     * @return the value of etl_task_cfg.cycle
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.cycle
     *
     * @param cycle the value for etl_task_cfg.cycle
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.priority
     *
     * @return the value of etl_task_cfg.priority
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.priority
     *
     * @param priority the value for etl_task_cfg.priority
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.if_recall
     *
     * @return the value of etl_task_cfg.if_recall
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getIfRecall() {
        return ifRecall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.if_recall
     *
     * @param ifRecall the value for etl_task_cfg.if_recall
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setIfRecall(Integer ifRecall) {
        this.ifRecall = ifRecall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.if_wait
     *
     * @return the value of etl_task_cfg.if_wait
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getIfWait() {
        return ifWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.if_wait
     *
     * @param ifWait the value for etl_task_cfg.if_wait
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setIfWait(Integer ifWait) {
        this.ifWait = ifWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.if_pre
     *
     * @return the value of etl_task_cfg.if_pre
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getIfPre() {
        return ifPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.if_pre
     *
     * @param ifPre the value for etl_task_cfg.if_pre
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setIfPre(Integer ifPre) {
        this.ifPre = ifPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.if_enable
     *
     * @return the value of etl_task_cfg.if_enable
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getIfEnable() {
        return ifEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.if_enable
     *
     * @param ifEnable the value for etl_task_cfg.if_enable
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setIfEnable(Integer ifEnable) {
        this.ifEnable = ifEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.freq
     *
     * @return the value of etl_task_cfg.freq
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.freq
     *
     * @param freq the value for etl_task_cfg.freq
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setFreq(String freq) {
        this.freq = freq == null ? null : freq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.owner
     *
     * @return the value of etl_task_cfg.owner
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.owner
     *
     * @param owner the value for etl_task_cfg.owner
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.wait_code
     *
     * @return the value of etl_task_cfg.wait_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getWaitCode() {
        return waitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.wait_code
     *
     * @param waitCode the value for etl_task_cfg.wait_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setWaitCode(String waitCode) {
        this.waitCode = waitCode == null ? null : waitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.recall_code
     *
     * @return the value of etl_task_cfg.recall_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getRecallCode() {
        return recallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.recall_code
     *
     * @param recallCode the value for etl_task_cfg.recall_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setRecallCode(String recallCode) {
        this.recallCode = recallCode == null ? null : recallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.success_code
     *
     * @return the value of etl_task_cfg.success_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getSuccessCode() {
        return successCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.success_code
     *
     * @param successCode the value for etl_task_cfg.success_code
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setSuccessCode(String successCode) {
        this.successCode = successCode == null ? null : successCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.timeout
     *
     * @return the value of etl_task_cfg.timeout
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.timeout
     *
     * @param timeout the value for etl_task_cfg.timeout
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.recall_interval
     *
     * @return the value of etl_task_cfg.recall_interval
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getRecallInterval() {
        return recallInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.recall_interval
     *
     * @param recallInterval the value for etl_task_cfg.recall_interval
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setRecallInterval(Integer recallInterval) {
        this.recallInterval = recallInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.log_file
     *
     * @return the value of etl_task_cfg.log_file
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getLogFile() {
        return logFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.log_file
     *
     * @param logFile the value for etl_task_cfg.log_file
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setLogFile(String logFile) {
        this.logFile = logFile == null ? null : logFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.add_user
     *
     * @return the value of etl_task_cfg.add_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.add_user
     *
     * @param addUser the value for etl_task_cfg.add_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setAddUser(String addUser) {
        this.addUser = addUser == null ? null : addUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.add_time
     *
     * @return the value of etl_task_cfg.add_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.add_time
     *
     * @param addTime the value for etl_task_cfg.add_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.update_user
     *
     * @return the value of etl_task_cfg.update_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.update_user
     *
     * @param updateUser the value for etl_task_cfg.update_user
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.update_time
     *
     * @return the value of etl_task_cfg.update_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.update_time
     *
     * @param updateTime the value for etl_task_cfg.update_time
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.type
     *
     * @return the value of etl_task_cfg.type
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.type
     *
     * @param type the value for etl_task_cfg.type
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.offset
     *
     * @return the value of etl_task_cfg.offset
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public String getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.offset
     *
     * @param offset the value for etl_task_cfg.offset
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setOffset(String offset) {
        this.offset = offset == null ? null : offset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.recall_limit
     *
     * @return the value of etl_task_cfg.recall_limit
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getRecallLimit() {
        return recallLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.recall_limit
     *
     * @param recallLimit the value for etl_task_cfg.recall_limit
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setRecallLimit(Integer recallLimit) {
        this.recallLimit = recallLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etl_task_cfg.concurrency
     *
     * @return the value of etl_task_cfg.concurrency
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public Integer getConcurrency() {
        return concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etl_task_cfg.concurrency
     *
     * @param concurrency the value for etl_task_cfg.concurrency
     *
     * @mbggenerated Fri Oct 09 12:36:28 CST 2015
     */
    public void setConcurrency(Integer concurrency) {
        this.concurrency = concurrency;
    }
}