package com.fanli.scheduler.entity;

public class MdsItemtableWithBLOBs extends MdsItemtable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.create_table_info
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String createTableInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.column_description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String columnDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.create_table_info
     *
     * @return the value of mds_itemtable.create_table_info
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getCreateTableInfo() {
        return createTableInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.create_table_info
     *
     * @param createTableInfo the value for mds_itemtable.create_table_info
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setCreateTableInfo(String createTableInfo) {
        this.createTableInfo = createTableInfo == null ? null : createTableInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.column_description
     *
     * @return the value of mds_itemtable.column_description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getColumnDescription() {
        return columnDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.column_description
     *
     * @param columnDescription the value for mds_itemtable.column_description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setColumnDescription(String columnDescription) {
        this.columnDescription = columnDescription == null ? null : columnDescription.trim();
    }
}