package com.fanli.scheduler.entity;

public class MdsItemtable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.table_id
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private Integer tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.table_name
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.blood_relation
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String bloodRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mds_itemtable.table_type
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    private String tableType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.table_id
     *
     * @return the value of mds_itemtable.table_id
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.table_id
     *
     * @param tableId the value for mds_itemtable.table_id
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.table_name
     *
     * @return the value of mds_itemtable.table_name
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.table_name
     *
     * @param tableName the value for mds_itemtable.table_name
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.description
     *
     * @return the value of mds_itemtable.description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.description
     *
     * @param description the value for mds_itemtable.description
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.blood_relation
     *
     * @return the value of mds_itemtable.blood_relation
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getBloodRelation() {
        return bloodRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.blood_relation
     *
     * @param bloodRelation the value for mds_itemtable.blood_relation
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setBloodRelation(String bloodRelation) {
        this.bloodRelation = bloodRelation == null ? null : bloodRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mds_itemtable.table_type
     *
     * @return the value of mds_itemtable.table_type
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mds_itemtable.table_type
     *
     * @param tableType the value for mds_itemtable.table_type
     *
     * @mbggenerated Mon Jul 27 14:59:59 CST 2015
     */
    public void setTableType(String tableType) {
        this.tableType = tableType == null ? null : tableType.trim();
    }
}